sudo: required
language: bash
services:
  - docker

# define the build matrix
env:
  global:
    - PROJECT_DIR: .
    - TOOLCHAIN: default
    - BUILD_PACKAGES: cmake
    - RUN_TESTS: false

matrix:
  include:
    # Linux {

    #   Ubuntu 16.04
    - os: linux
      env: >
        BUILD_FLAVOR=ubuntu
        BUILD_RELEASE=xenial
        BUILD_ARCH=amd64
    - os: linux
      env: >
        BUILD_FLAVOR=ubuntu
        BUILD_RELEASE=bionic
        BUILD_ARCH=amd64
    - os: linux
      env: >
        BUILD_FLAVOR=ubuntu
        BUILD_RELEASE=bionic
        BUILD_ARCH=amd64
        TOOLCHAIN=gcc-cxx17

    # Debian 8
    - os: linux
      env: >
        BUILD_FLAVOR=debian
        BUILD_RELEASE=stretch
        BUILD_ARCH=amd64
    # } // end Linux

before_install:
  # use the Dockerfile.<distro>.template file for building the image with sed magic
  - |
    sed \
    -e "s/@BUILD_FLAVOR@/${BUILD_FLAVOR}/g" \
    -e "s/@BUILD_RELEASE@/${BUILD_RELEASE}/g" \
    -e "s/@BUILD_ARCH@/${BUILD_ARCH}/g" \
    -e "s/@BUILD_PACKAGES@/${BUILD_PACKAGES}/g" \
    ci/Dockerfile.$BUILD_FLAVOR.template | tee ci/Dockerfile.$BUILD_FLAVOR.$BUILD_RELEASE.$BUILD_ARCH
  - docker build -f ci/Dockerfile.$BUILD_FLAVOR.$BUILD_RELEASE.$BUILD_ARCH -t glog-devel .

script: |
  # run the respective .travis.<distro>.sh script
  docker run \
  -e BUILD_FLAVOR="$BUILD_FLAVOR" \
  -e BUILD_RELEASE="$BUILD_RELEASE" \
  -e BUILD_ARCH="$BUILD_ARCH" \
  -e PROJECT_DIR="$PROJECT_DIR" \
  -e TOOLCHAIN="$TOOLCHAIN" \
  -e RUN_TESTS="$RUN_TESTS" \
  -it glog-devel ./ci/travis.$BUILD_FLAVOR.sh

